"""書類テンプレートの中央レジストリ。

submission_engine から分離し、テンプレート定義のみを管理する。
新しいテンプレート追加時はこのファイルにエントリを追記する。

エントリ形式:
    "template_key": {
        "file": "テンプレートのHTMLファイル名",
        "label_ja": "日本語のラベル",
        "label_en": "英語のラベル",
        "category": "カテゴリ (green_file / plan / payment / 等)",
        "required_fields": [...],
        "default_context": {...},  # (optional) 既定で注入する値
    }
"""

from typing import Any


# ── テンプレートレジストリ ──────────────────────────────────────────────────
# template_type → { file, label_ja, label_en, category, required_fields }
TEMPLATE_REGISTRY: dict[str, dict[str, Any]] = {
    # 既存
    "process_completion": {
        "file": "process_completion.html",
        "label_ja": "工程完了報告書",
        "label_en": "Process Completion Report",
        "category": "general",
        "required_fields": ["project", "phase", "photos", "reports"],
    },
    # ── 協議・確認系 ──
    "kouji_uchiawasebo": {
        "file": "kouji_uchiawasebo.html",
        "label_ja": "工事打合簿",
        "label_en": "Construction Meeting Minutes",
        "category": "coordination",
        "required_fields": ["project", "meeting_date", "subject", "content"],
    },
    "dankai_kakuninsho": {
        "file": "dankai_kakuninsho.html",
        "label_ja": "段階確認書",
        "label_en": "Stage Confirmation Document",
        "category": "inspection",
        "required_fields": ["project", "work_type", "location", "stage_name", "check_items"],
    },
    "zairyo_kakuninsho": {
        "file": "zairyo_kakuninsho.html",
        "label_ja": "材料確認書",
        "label_en": "Material Confirmation Document",
        "category": "material",
        "required_fields": ["project", "materials", "confirmation_date"],
    },
    # ── 計画系 ──
    "sekou_keikakusho": {
        "file": "sekou_keikakusho.html",
        "label_ja": "施工計画書",
        "label_en": "Construction Plan",
        "category": "plan",
        "required_fields": ["project", "organization", "construction_method"],
    },
    "hinshitsu_kanrihyo": {
        "file": "hinshitsu_kanrihyo.html",
        "label_ja": "品質管理表",
        "label_en": "Quality Control Table",
        "category": "quality",
        "required_fields": ["project", "quality_items"],
    },
    "anzen_kanri_keikakusho": {
        "file": "anzen_kanri_keikakusho.html",
        "label_ja": "安全管理計画書",
        "label_en": "Safety Management Plan",
        "category": "safety",
        "required_fields": ["project", "safety_manager", "risk_assessments"],
    },
    # ── 体制系 ──
    "sekou_taisei_daicho": {
        "file": "sekou_taisei_daicho.html",
        "label_ja": "施工体制台帳",
        "label_en": "Construction Organization Ledger",
        "category": "organization",
        "required_fields": ["project", "subcontractors"],
    },
    "sekou_taikeizu": {
        "file": "sekou_taikeizu.html",
        "label_ja": "施工体系図",
        "label_en": "Construction Organization Chart",
        "category": "organization",
        "required_fields": ["project", "subcontractors"],
    },
    "shitauke_hensei": {
        "file": "shitauke_hensei.html",
        "label_ja": "下請負業者編成表",
        "label_en": "Subcontractor Organization Table",
        "category": "organization",
        "required_fields": ["project", "subcontractors"],
    },
    # ── 管理図・帳票 ──
    "dekigata_kanrizu": {
        "file": "dekigata_kanrizu.html",
        "label_ja": "出来形管理図",
        "label_en": "As-Built Management Chart",
        "category": "quality",
        "required_fields": ["project", "work_type", "measurements"],
    },
    "saisei_shigen": {
        "file": "saisei_shigen.html",
        "label_ja": "再生資源利用計画書",
        "label_en": "Recycled Resource Utilization Plan",
        "category": "environment",
        "required_fields": ["project", "recycled_materials", "waste_materials"],
    },
    "koteihyo": {
        "file": "koteihyo.html",
        "label_ja": "工程表",
        "label_en": "Schedule Chart",
        "category": "plan",
        "required_fields": ["project", "schedule_tasks"],
    },
    # ── 日常記録 ──
    "kouji_nisshi": {
        "file": "kouji_nisshi.html",
        "label_ja": "工事日誌",
        "label_en": "Construction Diary",
        "category": "daily",
        "required_fields": ["project", "diary_date", "weather_am", "weather_pm", "works"],
    },
    "kouji_shashincho": {
        "file": "kouji_shashincho.html",
        "label_ja": "工事写真帳",
        "label_en": "Construction Photo Album",
        "category": "photo",
        "required_fields": ["project", "photos"],
    },
    # ── 出来高・検査 ──
    "dekidaka_houkokusho": {
        "file": "dekidaka_houkokusho.html",
        "label_ja": "出来高報告書",
        "label_en": "Progress Payment Report",
        "category": "payment",
        "required_fields": ["project", "report_period_start", "report_period_end", "progress_items"],
    },
    "kensa_kiroku": {
        "file": "kensa_kiroku.html",
        "label_ja": "検査記録",
        "label_en": "Inspection Record",
        "category": "inspection",
        "required_fields": ["project", "inspection_type", "inspection_date", "inspection_items"],
    },
    # ── 是正・NCR ──
    "zesei_sochi": {
        "file": "zesei_sochi.html",
        "label_ja": "是正措置報告書（NCR）",
        "label_en": "Corrective Action Report (NCR)",
        "category": "quality",
        "required_fields": ["project", "nonconformity_description", "root_cause", "corrective_actions"],
    },
    # ── 安全系 ──
    "anzen_junkai": {
        "file": "anzen_junkai.html",
        "label_ja": "安全巡回記録",
        "label_en": "Safety Patrol Record",
        "category": "safety",
        "required_fields": ["project", "patrol_datetime", "patrol_by", "check_items"],
    },
    "shinki_nyujousha": {
        "file": "shinki_nyujousha.html",
        "label_ja": "新規入場者教育記録",
        "label_en": "New Worker Orientation Record",
        "category": "safety",
        "required_fields": ["project", "education_datetime", "attendees"],
    },
    "ky_katsudo": {
        "file": "ky_katsudo.html",
        "label_ja": "KY活動記録",
        "label_en": "KY Activity Record",
        "category": "safety",
        "required_fields": ["project", "activity_date", "work_group", "leader"],
    },
    "hiyarihatto": {
        "file": "hiyarihatto.html",
        "label_ja": "ヒヤリハット報告書",
        "label_en": "Near-Miss Report",
        "category": "safety",
        "required_fields": ["project", "incident_datetime", "reporter_name", "incident_description"],
    },
    # ── 廃棄物 ──
    "sanpai_kanrihyo": {
        "file": "sanpai_kanrihyo.html",
        "label_ja": "産業廃棄物管理票（マニフェスト）",
        "label_en": "Waste Manifest",
        "category": "environment",
        "required_fields": ["project", "wastes", "transporter_name", "disposer_name"],
    },
    # ── 材料試験 ──
    "zairyo_shiken": {
        "file": "zairyo_shiken.html",
        "label_ja": "材料試験成績書",
        "label_en": "Material Test Results",
        "category": "quality",
        "required_fields": ["project", "material_name", "test_items"],
    },
    "concrete_dasetsu": {
        "file": "concrete_dasetsu.html",
        "label_ja": "コンクリート打設記録",
        "label_en": "Concrete Placement Record",
        "category": "quality",
        "required_fields": ["project", "placement_date", "placement_location", "fresh_tests"],
    },
    "haikin_kensa": {
        "file": "haikin_kensa.html",
        "label_ja": "配筋検査記録",
        "label_en": "Rebar Inspection Record",
        "category": "inspection",
        "required_fields": ["project", "inspection_date", "inspection_location", "main_bars"],
    },
    "tekko_kensa": {
        "file": "tekko_kensa.html",
        "label_ja": "鉄骨工事検査記録",
        "label_en": "Steel Structure Inspection Record",
        "category": "inspection",
        "required_fields": ["project", "inspection_date", "inspection_location", "steel_materials"],
    },
    "bosui_kensa": {
        "file": "bosui_kensa.html",
        "label_ja": "防水工事検査記録",
        "label_en": "Waterproofing Inspection Record",
        "category": "inspection",
        "required_fields": ["project", "inspection_date", "waterproof_method", "materials"],
    },
    # ── 変更・完成 ──
    "sekkei_henko": {
        "file": "sekkei_henko.html",
        "label_ja": "設計変更協議書",
        "label_en": "Design Change Consultation",
        "category": "change",
        "required_fields": ["project", "change_reason", "change_items"],
    },
    "kouji_kansei": {
        "file": "kouji_kansei.html",
        "label_ja": "工事完成届",
        "label_en": "Construction Completion Notice",
        "category": "completion",
        "required_fields": ["project", "actual_completion_date", "main_work_content"],
    },
    "hikiwatashi": {
        "file": "hikiwatashi.html",
        "label_ja": "引渡書",
        "label_en": "Handover Document",
        "category": "completion",
        "required_fields": ["project", "handover_date", "actual_completion_date"],
    },
    # ── グリーンファイル (全建統一様式) ──────────────────────
    "sagyoin_meibo": {
        "file": "sagyoin_meibo.html",
        "label_ja": "作業員名簿",
        "label_en": "Worker Roster",
        "category": "green_file",
        "required_fields": ["project", "company_name", "workers"],
    },
    "kensetsu_kaizen_todoke": {
        "file": "kensetsu_kaizen_todoke.html",
        "label_ja": "建設業法・雇用改善法等に基づく届出書",
        "label_en": "Construction Law / Employment Improvement Notification",
        "category": "green_file",
        "required_fields": ["project", "company_name", "license_number"],
    },
    "romu_anzen_seiyaku": {
        "file": "romu_anzen_seiyaku.html",
        "label_ja": "労務安全等に関する誓約書",
        "label_en": "Labor Safety Pledge",
        "category": "green_file",
        "required_fields": ["project", "company_name", "representative"],
    },
    "taisei_daicho_tsuchi": {
        "file": "taisei_daicho_tsuchi.html",
        "label_ja": "施工体制台帳作成建設工事の通知",
        "label_en": "Construction Organization Ledger Creation Notice",
        "category": "green_file",
        "required_fields": ["project", "subcontractor_name", "company_name"],
    },
    "mochikomi_crane": {
        "file": "mochikomi_crane.html",
        "label_ja": "持込機械等(車両系建設機械等)使用届",
        "label_en": "Brought-in Machinery (Crane) Usage Notification",
        "category": "green_file",
        "required_fields": ["project", "company_name", "machines"],
    },
    "mochikomi_denki_kogu": {
        "file": "mochikomi_denki_kogu.html",
        "label_ja": "持込機械等(電動工具・電気溶接機等)使用届",
        "label_en": "Brought-in Machinery (Electric Tools) Usage Notification",
        "category": "green_file",
        "required_fields": ["project", "company_name", "tools"],
    },
    "kojiyou_sharyou": {
        "file": "kojiyou_sharyou.html",
        "label_ja": "工事用車両届",
        "label_en": "Construction Vehicle Notification",
        "category": "green_file",
        "required_fields": ["project", "company_name", "vehicles"],
    },
    "yuki_yozai_todoke": {
        "file": "yuki_yozai_todoke.html",
        "label_ja": "有機溶剤・特定化学物質等持込使用届",
        "label_en": "Organic Solvent / Hazardous Chemical Notification",
        "category": "green_file",
        "required_fields": ["project", "company_name", "chemicals"],
    },
    "kaki_shiyou_negai": {
        "file": "kaki_shiyou_negai.html",
        "label_ja": "火気使用願",
        "label_en": "Fire Use Permit",
        "category": "green_file",
        "required_fields": ["project", "company_name", "start_datetime", "location"],
    },
    "jigyou_anzen_keikaku": {
        "file": "jigyou_anzen_keikaku.html",
        "label_ja": "事業所安全衛生管理計画書",
        "label_en": "Site Safety & Health Management Plan",
        "category": "green_file",
        "required_fields": ["project", "company_name", "safety_goal"],
    },
    "okuridashi_kyouiku": {
        "file": "okuridashi_kyouiku.html",
        "label_ja": "送り出し教育実施報告書",
        "label_en": "Pre-Dispatch Education Report",
        "category": "green_file",
        "required_fields": ["project", "sender_company", "education_date"],
    },
    "nensho_kourei_houkoku": {
        "file": "nensho_kourei_houkoku.html",
        "label_ja": "年少者・高年齢者就労報告書",
        "label_en": "Minor / Elderly Worker Employment Report",
        "category": "green_file",
        "required_fields": ["project", "company_name", "workers"],
    },
    "ashiba_tenken": {
        "file": "ashiba_tenken.html",
        "label_ja": "足場作業前点検チェックリスト",
        "label_en": "Scaffold Pre-Work Inspection Checklist",
        "category": "green_file",
        "required_fields": ["project", "inspection_date", "inspector"],
    },
    "anzen_keikaku_nenkan": {
        "file": "anzen_keikaku_nenkan.html",
        "label_ja": "建設業における安全衛生管理年間計画書",
        "label_en": "Annual Construction Safety & Health Management Plan",
        "category": "green_file",
        "required_fields": ["project", "company_name", "fiscal_year"],
    },
    # ── 新規入場者調査票 (全建統一参考様式 第4号) ──
    "shinki_nyuujou_chosashou": {
        "file": "shinki_nyuujou_chosashou.html",
        "label_ja": "新規入場者調査票",
        "label_en": "New Worker Entry Survey",
        "category": "green_file",
        "required_fields": ["project", "name", "entry_date"],
    },
    # ── 大規模改修工事 詳細見積書 (出来高調書付き) ──
    "kaisyu_mitsumori_detail": {
        "file": "kaisyu_mitsumori_detail.html",
        "label_ja": "大規模改修工事 見積書(出来高調書付)",
        "label_en": "Large-scale Renovation Estimate (with Progress Ledger)",
        "category": "payment",
        "required_fields": ["project", "company_name", "sections"],
    },
    # ── 工種別 施工計画書 (7工種) — 共通テンプレに default_context で work_type を注入 ──
    "kosyu_keikaku_gaiheki": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "外壁改修工事 施工計画書",
        "label_en": "Exterior Wall Renovation Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "外壁改修"},
    },
    "kosyu_keikaku_bosui": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "防水改修工事 施工計画書",
        "label_en": "Waterproofing Renovation Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "防水改修"},
    },
    "kosyu_keikaku_tosou": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "塗装工事 施工計画書",
        "label_en": "Painting Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "塗装"},
    },
    "kosyu_keikaku_tile": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "タイル工事 施工計画書",
        "label_en": "Tile Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "タイル"},
    },
    "kosyu_keikaku_sealing": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "シーリング工事 施工計画書",
        "label_en": "Sealing Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "シーリング"},
    },
    "kosyu_keikaku_ashiba": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "足場組立解体 施工計画書",
        "label_en": "Scaffold Assembly/Dismantle Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "足場組立解体"},
    },
    "kosyu_keikaku_asbestos": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "アスベスト除去 施工計画書",
        "label_en": "Asbestos Removal Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "アスベスト除去"},
    },
    # ── 工種別施工計画書 追加分 (改修工事で頻出) ──
    "kosyu_keikaku_sougou": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "総合施工計画書",
        "label_en": "Comprehensive Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "総合"},
    },
    "kosyu_keikaku_kasetsu": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "仮設工事 施工計画書",
        "label_en": "Temporary Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "仮設工事"},
    },
    "kosyu_keikaku_seet_bosui": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "シート防水工事 施工計画書",
        "label_en": "Sheet Waterproofing Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "シート防水"},
    },
    "kosyu_keikaku_tomaku_bosui": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "塗膜防水工事 施工計画書",
        "label_en": "Coating Waterproofing Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "塗膜防水"},
    },
    "kosyu_keikaku_asphalt_bosui_kaisyu": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "アスファルト防水改修工事 施工計画書",
        "label_en": "Asphalt Waterproofing Renovation Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "アスファルト防水改修"},
    },
    "kosyu_keikaku_fukitsuke": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "吹付け塗装工事 施工計画書",
        "label_en": "Spray Painting Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "吹付け塗装"},
    },
    "kosyu_keikaku_yane": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "屋根工事 施工計画書",
        "label_en": "Roof Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "屋根工事"},
    },
    "kosyu_keikaku_haisui": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "排水工事 施工計画書",
        "label_en": "Drainage Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "排水工事"},
    },
    "kosyu_keikaku_kaitai": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "解体工事 施工計画書",
        "label_en": "Demolition Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "解体工事"},
    },
    "kosyu_keikaku_tategu": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "建具工事 施工計画書",
        "label_en": "Joinery Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "建具工事"},
    },
    "kosyu_keikaku_glass": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "ガラス工事 施工計画書",
        "label_en": "Glass Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "ガラス工事"},
    },
    "kosyu_keikaku_naisou": {
        "file": "kosyu_keikakusho.html",
        "label_ja": "内装工事 施工計画書",
        "label_en": "Interior Construction Plan",
        "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "内装工事"},
    },
    # ── KY活動 / 作業日報 の追加バリアント (新サンプル準拠) ──
    "ky_risk_assessment": {
        "file": "ky_risk_assessment.html",
        "label_ja": "KY活動表（リスク見積足し算式）",
        "label_en": "KY Risk Assessment (Additive Method)",
        "category": "safety",
        "required_fields": ["project", "activity_date", "work_content"],
    },
    "sagyou_nippou_detail": {
        "file": "sagyou_nippou_detail.html",
        "label_ja": "作業日報（作業員別時間管理付）",
        "label_en": "Work Daily Report (with Worker Time Tracking)",
        "category": "daily",
        "required_fields": ["project", "report_date"],
    },
    # ── 残り17工種 (38工種網羅) ──
    "kosyu_keikaku_ishi": {
        "file": "kosyu_keikakusho.html", "label_ja": "石工事 施工計画書",
        "label_en": "Stone Work Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "石工事"},
    },
    "kosyu_keikaku_moku": {
        "file": "kosyu_keikakusho.html", "label_ja": "木工事 施工計画書",
        "label_en": "Wood Work Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "木工事"},
    },
    "kosyu_keikaku_kinzoku_yane": {
        "file": "kosyu_keikakusho.html", "label_ja": "金属板葺屋根工事 施工計画書",
        "label_en": "Metal Roof Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "金属板葺屋根"},
    },
    "kosyu_keikaku_kawara": {
        "file": "kosyu_keikakusho.html", "label_ja": "瓦葺屋根工事 施工計画書",
        "label_en": "Tile Roof Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "瓦葺屋根"},
    },
    "kosyu_keikaku_shingle_yane": {
        "file": "kosyu_keikakusho.html", "label_ja": "アスファルトシングル葺屋根工事 施工計画書",
        "label_en": "Asphalt Shingle Roof Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "アスファルトシングル葺屋根"},
    },
    "kosyu_keikaku_toi": {
        "file": "kosyu_keikakusho.html", "label_ja": "とい工事 施工計画書",
        "label_en": "Gutter Work Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "とい工事"},
    },
    "kosyu_keikaku_kinzoku": {
        "file": "kosyu_keikakusho.html", "label_ja": "金属工事 施工計画書",
        "label_en": "Metal Work Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "金属工事"},
    },
    "kosyu_keikaku_sakan": {
        "file": "kosyu_keikakusho.html", "label_ja": "左官工事 施工計画書",
        "label_en": "Plastering Work Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "左官工事"},
    },
    "kosyu_keikaku_tategu_al": {
        "file": "kosyu_keikakusho.html", "label_ja": "アルミニウム製建具工事 施工計画書",
        "label_en": "Aluminum Joinery Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "アルミニウム製建具"},
    },
    "kosyu_keikaku_tategu_steel": {
        "file": "kosyu_keikakusho.html", "label_ja": "鋼製建具工事 施工計画書",
        "label_en": "Steel Joinery Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "鋼製建具"},
    },
    "kosyu_keikaku_tategu_steel_light": {
        "file": "kosyu_keikakusho.html", "label_ja": "鋼製軽量建具工事 施工計画書",
        "label_en": "Lightweight Steel Joinery Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "鋼製軽量建具"},
    },
    "kosyu_keikaku_tategu_stainless": {
        "file": "kosyu_keikakusho.html", "label_ja": "ステンレス製建具工事 施工計画書",
        "label_en": "Stainless Joinery Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "ステンレス製建具"},
    },
    "kosyu_keikaku_tategu_wood": {
        "file": "kosyu_keikakusho.html", "label_ja": "木製建具工事 施工計画書",
        "label_en": "Wood Joinery Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "木製建具"},
    },
    "kosyu_keikaku_resin_floor": {
        "file": "kosyu_keikakusho.html", "label_ja": "合成樹脂塗床 施工計画書",
        "label_en": "Resin Floor Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "合成樹脂塗床"},
    },
    "kosyu_keikaku_board": {
        "file": "kosyu_keikakusho.html", "label_ja": "せっこうボード・ボード工事 施工計画書",
        "label_en": "Gypsum Board Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "せっこうボード"},
    },
    "kosyu_keikaku_kabe_kami": {
        "file": "kosyu_keikakusho.html", "label_ja": "壁紙貼り 施工計画書",
        "label_en": "Wallpaper Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "壁紙貼り"},
    },
    "kosyu_keikaku_yuka_hari": {
        "file": "kosyu_keikakusho.html", "label_ja": "床張り 施工計画書",
        "label_en": "Floor Laying Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "床張り"},
    },
    "kosyu_keikaku_flooring": {
        "file": "kosyu_keikakusho.html", "label_ja": "フローリング 施工計画書",
        "label_en": "Flooring Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "フローリング"},
    },
    "kosyu_keikaku_toilet_booth": {
        "file": "kosyu_keikakusho.html", "label_ja": "トイレブース工事 施工計画書",
        "label_en": "Toilet Booth Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "トイレブース"},
    },
    "kosyu_keikaku_lgs_wall": {
        "file": "kosyu_keikakusho.html", "label_ja": "軽鉄壁下地 施工計画書",
        "label_en": "LGS Wall Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "軽鉄壁下地"},
    },
    "kosyu_keikaku_lgs_ceiling": {
        "file": "kosyu_keikakusho.html", "label_ja": "軽鉄天井下地 施工計画書",
        "label_en": "LGS Ceiling Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "軽鉄天井下地"},
    },
    "kosyu_keikaku_unit_bath": {
        "file": "kosyu_keikakusho.html", "label_ja": "ユニットバス 施工計画書",
        "label_en": "Unit Bath Plan", "category": "plan",
        "required_fields": ["project", "company_name"],
        "default_context": {"work_type": "ユニットバス"},
    },
}

