"""add subcontractor trade and contact_person

Revision ID: 4c858dee12d4
Revises: 71db2324c75e
Create Date: 2026-05-04 13:36:34.399329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c858dee12d4'
down_revision: Union[str, Sequence[str], None] = '71db2324c75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcontractors', sa.Column('contact_person', sa.String(length=255), nullable=True))
    op.add_column('subcontractors', sa.Column('trade', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcontractors', 'trade')
    op.drop_column('subcontractors', 'contact_person')
    # ### end Alembic commands ###
