"""add tenant_id to safety models

Revision ID: 71db2324c75e
Revises: fd437c89ed2b
Create Date: 2026-05-04 13:16:07.644213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71db2324c75e'
down_revision: Union[str, Sequence[str], None] = 'fd437c89ed2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_reports', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.add_column('ky_activities', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.add_column('safety_patrols', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.add_column('safety_trainings', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('safety_trainings', 'tenant_id')
    op.drop_column('safety_patrols', 'tenant_id')
    op.drop_column('ky_activities', 'tenant_id')
    op.drop_column('incident_reports', 'tenant_id')
    # ### end Alembic commands ###
